### ISSUE TITLE
[FR] missing title in week06

### ISSUE THREAD

**Issue by AliEl-01** [Atcold/pytorch-Deep-Learning#539] opened 2020-09-13 17:01 UTC
the title (Batch-Ification in Language Modeling) is missing in (06-3.md)

**Comment by Atcold** [comment] 2020-09-13 20:17
@lbourdois, send a PR when you can.
Have the commit message including `close #539` to automatically close this issue at merging time.

**Comment by Atcold** [comment] 2020-09-13 20:25
Also, images and math are not showing up… 😕
The automatic translation utility used fucked up badly…

**Comment by lbourdois** [comment] 2020-09-13 20:28
@AliEl-01 @Atcold 

Did I miss something? Because I don't understand what the problem is. The title is [there](https://github.com/Atcold/pytorch-Deep-Learning/blob/master/docs/fr/week06/06-3.md)

**Comment by lbourdois** [comment] 2020-09-13 20:40
> Also, images and math are not showing up… 😕
> The automatic translation utility used fucked up badly…

@Atcold 
What appears on the site is my first PR (#502). The corrections you merged a few hours ago (#535) don't appear on the site (the files in the repo are correct). Is there a delay to wait to see the changes on the site  or is a new problem to solve :weary: ?

**Comment by AliEl-01** [comment] 2020-09-13 21:23
Oh ok sorry I saw just the site page soo I declared this issue. I'm sorry again 🙏🏻

**Closed** 2020-09-13 21:25 UTC
