### ISSUE TITLE
[ZH] 13-3 Inline latex broken

### ISSUE THREAD

**Issue by xcastilla** [Atcold/pytorch-Deep-Learning#618] opened 2020-09-23 13:45 UTC
Hi @JonathanSum ! Just for your info,
There seems to be some inline latex broken on lecture 13-3:

<img width="889" alt="Screen Shot 2020-09-23 at 22 41 44" src="https://user-images.githubusercontent.com/11987768/94020729-37e4b280-fdee-11ea-91c2-2efa9a284d53.png">

The rest of the lectures I've checked seem to be fine.

**Comment by JonathanSum** [comment] 2020-09-23 16:50
I tried to fix it, but it looks like the latex is the same as the one in English version.

**Comment by JonathanSum** [comment] 2020-09-23 17:02
在自我注意力机制中，我们有一个输入集$\lbrace\boldsymbol{x}\_{i}\rbrace^{t}_{i=1}$。不像序列那样，它没有顺序的。
隐藏向量$\boldsymbol{h}$是由集之中的向量的线性组合得出来的。
我们可以用矩阵向量乘法来以$\boldsymbol{X}\boldsymbol{a}$去表达这个东西，这里$\boldsymbol{a}$包含一些会缩放向量$\boldsymbol{x}_{i}$的系数。



- In self-attention, we have a set of input $\lbrace\boldsymbol{x}\_{i}\rbrace^{t}_{i=1}$.
Unlike a sequence, it does not have an order.
- Hidden vector $\boldsymbol{h}$ is given by linear combination of the vectors in the set.
- We can express this as $\boldsymbol{X}\boldsymbol{a}$ using matrix vector multiplication, where $\boldsymbol{a}$ contains coefficients that scale the input vector $\boldsymbol{x}_{i}$.

They look the same.

$\lbrace\boldsymbol{x}\_{i}\rbrace^{t}_{i=1}$
$\lbrace\boldsymbol{x}\_{i}\rbrace^{t}_{i=1}$

$\boldsymbol{h}$
$\boldsymbol{h}$

$\boldsymbol{X}\boldsymbol{a}$
$\boldsymbol{X}\boldsymbol{a}$

$\boldsymbol{a}$ 
$\boldsymbol{a}$

$\boldsymbol{x}_{i}$
$\boldsymbol{x}_{i}$

**Comment by JonathanSum** [comment] 2020-09-23 17:03
Oh. I think I see the problem.

**Comment by JonathanSum** [comment] 2020-09-23 17:06
I can't fix it. Github thinks the latex is the same as the one in English. Thus, I can't make any changes to the GitHub file.

**Comment by JonathanSum** [comment] 2020-09-23 17:10
https://github.com/Atcold/pytorch-Deep-Learning/pull/619

**Comment by Atcold** [comment] 2020-09-23 17:13
@JonathanSum, you may have to escape the `_` like `\_`. Let me know if it works.

**Comment by JonathanSum** [comment] 2020-09-23 17:52
@Atcold, I checked it. The latex is the same as the English one.

**Comment by JonathanSum** [comment] 2020-09-24 04:57
I have checked the Latex. It is using` \_` rather `_`, and the Chinese version has an issue. Should we change it back to `_`

**Comment by JonathanSum** [comment] 2020-10-01 20:24
I have tested on my Github repo by randomly putting the latex at the place the latex is broken. I guess the problem can be solved by changing the "，" to be ' , '。 That is because I think the issue is caused by the Chinese comma, so it can be solved by using an English comma.

**Comment by JonathanSum** [comment] 2020-10-11 05:09
![Uploading image.png…]()

**Comment by Atcold** [comment] 2020-11-25 03:44
Was this fixed?

**Comment by JonathanSum** [comment] 2020-11-25 05:06
I dont know.  I guess not and you can check it at 13_3

**Comment by JonathanSum** [comment] 2020-11-25 06:42
I just found one of two latex issue is fixed on my repo. I will try to fix the two of two latex issues with the way to solve one of two latex issues.
![image](https://user-images.githubusercontent.com/21982975/100192165-4448c280-2ea6-11eb-98fb-3a7db95e546c.png)

**Comment by JonathanSum** [comment] 2020-11-25 09:10
@https://github.com/Atcold/pytorch-Deep-Learning/pull/697

**Comment by Atcold** [comment] 2020-12-11 02:31
Thank, going over the PRs right now.

**Comment by JonathanSum** [comment] 2020-12-11 06:09
Problems are solved. I think we can close it. 
You can see it here: https://atcold.github.io/pytorch-Deep-Learning/zh/week13/13-3/

**Closed** 2020-12-11 06:34 UTC
